#pragma once

#define GRIDSIZEX	30
#define GRIDSIZEY	25
#define GRIDSIZE GRIDSIZEX * GRIDSIZEY

#define SPRITESHEETFILENAME "urban.png"
#define SPRITESHEETX 4
#define SPRITESHEETY 4
#define TILEAMOUNT	16
#define TILESIZE 32.0f